In [1]:
from mxnet import nd

- In mxnet, scalars are NDArrays with one element.

In [2]:
x = nd.array([2])
x


[2.]
<NDArray 1 @cpu(0)>

In [3]:
print(x.shape)

(1,)


- NDArray can be converted to python float by calling its asscalar method

In [4]:
print(x)
print(x.asscalar())


[2.]
<NDArray 1 @cpu(0)>
2.0


- we can transpose the matrix through T

In [6]:
A = nd.arange(10).reshape(2,-1)
print(A)
print(A.T)


[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
<NDArray 2x5 @cpu(0)>

[[0. 5.]
 [1. 6.]
 [2. 7.]
 [3. 8.]
 [4. 9.]]
<NDArray 5x2 @cpu(0)>


- we can call nd.sum to compute the sum of NDArray

In [8]:
# sum of all elements of A
print(nd.sum(A))


[45.]
<NDArray 1 @cpu(0)>


In [9]:
# sum of element of A along dim 0
print(nd.sum(A,0))


[ 5.  7.  9. 11. 13.]
<NDArray 5 @cpu(0)>


- We can use nd.dot() to perform the vector dot product and matrix-vector product and matrix-matrix product

In [10]:
x = nd.arange(4) + 1
y = nd.ones(4)
print(x,y,nd.dot(x,y))


[1. 2. 3. 4.]
<NDArray 4 @cpu(0)> 
[1. 1. 1. 1.]
<NDArray 4 @cpu(0)> 
[10.]
<NDArray 1 @cpu(0)>


In [12]:
A = nd.arange(12).reshape((3,4))
print(A, nd.dot(A,x))


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)> 
[ 20.  60. 100.]
<NDArray 3 @cpu(0)>


In [14]:
print("A:=",A)
print("x:",x)
# using broadcasting mechanism
print("A*x:",A*x)

A:= 
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>
x: 
[1. 2. 3. 4.]
<NDArray 4 @cpu(0)>
A*x: 
[[ 0.  2.  6. 12.]
 [ 4. 10. 18. 28.]
 [ 8. 18. 30. 44.]]
<NDArray 3x4 @cpu(0)>


In [17]:
A = A.reshape((4,3))
x = x.reshape((4,1))
print("A:=",A)
print("x:",x)
# using broadcasting mechanism
print("A*x:",A*x)

A:= 
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
<NDArray 4x3 @cpu(0)>
x: 
[[1.]
 [2.]
 [3.]
 [4.]]
<NDArray 4x1 @cpu(0)>
A*x: 
[[ 0.  1.  2.]
 [ 6.  8. 10.]
 [18. 21. 24.]
 [36. 40. 44.]]
<NDArray 4x3 @cpu(0)>
