In [1]:
import mxnet as mx
from mxnet import nd

- `arange` creates a row vector:

In [2]:
x = nd.arange(10)
x


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
<NDArray 10 @cpu(0)>

- query the shape of a NDArray

In [3]:
x.shape

(10,)

- query the size of a NDArray

In [5]:
x.size

10

- reshape the shape of a NDArray
- we can use -1 to fill in defaults.

In [10]:
x = x.reshape(-1,5)
print(x)
print(x.shape)


[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
<NDArray 2x5 @cpu(0)>
(2, 5)


- empty method creates the uninitialized array

In [12]:
nd.empty((3,4))


[[0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 3.295854e-42 0.000000e+00]
 [0.000000e+00 4.132760e-39 0.000000e+00 9.275548e-39]]
<NDArray 3x4 @cpu(0)>

- zeros method creates an array with all zeros

In [13]:
nd.zeros((3,4))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

- ones method creates an array with all ones

In [14]:
nd.ones((3,4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

- we can create NDArray by python list

In [15]:
y = nd.array([[1,2],[2,3],[3,4]])
y


[[1. 2.]
 [2. 3.]
 [3. 4.]]
<NDArray 3x2 @cpu(0)>

- normal method generates a normal distribution

In [17]:
# zero mean, unit variance
x = nd.random.normal(0, 1, shape=(3,4))
x


[[-0.68106437 -0.1353156   0.37723133  0.41016456]
 [ 0.5712682  -2.7579627   1.07628    -0.6141325 ]
 [ 1.8307649  -1.1468065   0.05383794 -2.5074806 ]]
<NDArray 3x4 @cpu(0)>

- standard arithmetic operators(such as +,-,*/) have all been lifted to element-wise operations.

In [18]:
x = nd.array([1,2,3])
# using the shape of x to create y
y = nd.ones_like(x)*3 
print("x=:",x)
print("y=:",y)
print("x+y=:", x+y)
print("x/y=:", x/y)

x=: 
[1. 2. 3.]
<NDArray 3 @cpu(0)>
y=: 
[3. 3. 3.]
<NDArray 3 @cpu(0)>
x+y=: 
[4. 5. 6.]
<NDArray 3 @cpu(0)>
x/y=: 
[0.33333334 0.6666667  1.        ]
<NDArray 3 @cpu(0)>


- use dot function for matrix operations

In [20]:
x = nd.arange(12).reshape((3,4))
y = nd.arange(2,14).reshape((3,4))
print("x:",x)
print("y:",y)
# shape error, the shape of y is (3,4)
#print(nd.dot(x,y))
print(nd.dot(x,y.T))

x: 
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>
y: 
[[ 2.  3.  4.  5.]
 [ 6.  7.  8.  9.]
 [10. 11. 12. 13.]]
<NDArray 3x4 @cpu(0)>

[[ 26.  50.  74.]
 [ 82. 170. 258.]
 [138. 290. 442.]]
<NDArray 3x3 @cpu(0)>


- use concat to merge multiple NDArrays

In [21]:
# along dim 0, vertical
nd.concat(x, y, dim=0)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 2.  3.  4.  5.]
 [ 6.  7.  8.  9.]
 [10. 11. 12. 13.]]
<NDArray 6x4 @cpu(0)>

In [22]:
# along dim 1, horizontal
nd.concat(x, y, dim=1)


[[ 0.  1.  2.  3.  2.  3.  4.  5.]
 [ 4.  5.  6.  7.  6.  7.  8.  9.]
 [ 8.  9. 10. 11. 10. 11. 12. 13.]]
<NDArray 3x8 @cpu(0)>

- use logical statement to construct binary array

In [23]:
x == y


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

- mxnet uses the same broadcast mechanism as numpy

In [25]:
a = nd.arange(3).reshape(3,1)
b = nd.arange(2).reshape(1,2)
a,b

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>, 
 [[0. 1.]]
 <NDArray 1x2 @cpu(0)>)

In [29]:
# a-> [[0,0], [1,1], [2,2]]
# b->[[0,1], [0,1], [0,1]]
print(a+b)
# equivalent to:
new_a = nd.array([[0,0], [1,1], [2,2]])
new_b = nd.array([[0,1], [0,1], [0,1]])
print(new_a+new_b)


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>


- use indexing and slicing to select the value from a NDArray

In [30]:
# row 0 and row 1
x[1:3]


[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>

In [32]:
# row 1 column 2
x[1,2] = 1000
x


[[   0.    1.    2.    3.]
 [   4.    5. 1000.    7.]
 [   8.    9.   10.   11.]]
<NDArray 3x4 @cpu(0)>

- assign multiple values

In [34]:
x[0:2,:] = 111
x


[[111. 111. 111. 111.]
 [111. 111. 111. 111.]
 [  8.   9.  10.  11.]]
<NDArray 3x4 @cpu(0)>

- in mxnet, the new memory is allocated for each operation. E.g., for y = x + y, after running, y will have a different location. That's because python first evaluates y+x, allocating new memory for the result and then redirects y to point at this new location.

In [35]:
before = id(y)
y = y + x
id(y) == before
print(id(y))
print(before)

2026218174168
2026210519528


- In mxnet, using the slice notation to run in-place operation.

In [36]:
z = y.zeros_like(y)
print("id(z):", id(z))
z[:] = x + y
print("id(z):", id(z))

id(z): 2026218174168
id(z): 2026218174168


- Transformation between NDArray and NumPy doesn't share memory. 

In [37]:
import numpy as np
a = x.asnumpy()
print(type(a))
b = nd.array(a)
print(type(b))

<class 'numpy.ndarray'>
<class 'mxnet.ndarray.ndarray.NDArray'>
